### PR TITLE
fix: correctly validate misaligned any1, any2, etc.

### LINKED ISSUE #172: Type parameter consistency not validated for `any1` (etc.) parameters
The library does not validate that arguments using constrained any parameters (e.g., `any1`) have matching concrete types.

The following test fails, when it should pass: 
```go
func TestAny1TypeParameterConsistency(t *testing.T) {
	reg := expr.NewEmptyExtensionRegistry(extensions.GetDefaultCollectionWithNoError())

	t.Run("non-variadic any1", func(t *testing.T) {
		equalID := extensions.ID{
			URN:  extensions.SubstraitDefaultURNPrefix + "functions_comparison",
			Name: "equal",
		}

		_, err := expr.NewScalarFunc(reg, equalID, nil,
			expr.NewPrimitiveLiteral(int32(5), false),
			expr.NewPrimitiveLiteral(int64(10), false))
		require.Error(t, err, "equal should reject mixed types (i32, i64)")
	})

	t.Run("variadic any1", func(t *testing.T) {
		coalesceID := extensions.ID{
			URN:  extensions.SubstraitDefaultURNPrefix + "functions_comparison",
			Name: "coalesce",
		}

		_, err := expr.NewScalarFunc(reg, coalesceID, nil,
			expr.NewPrimitiveLiteral(int32(5), false),
			expr.NewPrimitiveLiteral(int64(10), false))
		require.Error(t, err, "coalesce should reject mixed types (i32, i64)")
	})
}
```

### PR DESCRIPTION
**Pull request by benbellick**
bump to substrait 0.78.1

Closes #172

### CODE REVIEW

File: extensions/variants_test.go [hunk 1]
```diff
@@ -470,3 +470,330 @@ func TestResolveTypeErrorHandling(t *testing.T) {
...
+			&types.Int32Type{},
+		}
+		variadic := &extensions.VariadicBehavior{Min: 2}
+
+		err := extensions.ValidateConstrainedAnyTypeConsistency(params, args, variadic)
+		require.NoError(t, err)
+	})
+
+	t.Run("variadic with mismatched types fails", func(t *testing.T) {
+		// func(any1, ...) with (i32, i64, i32)
```
Comment (asolimando) [inline extensions/variants_test.go]: Maybe an extra test with `func(any1, any2, ...)`?

Similar to `func(any1, any2, any1, ...) with (i32, string, i64, i32)` below but not exactly the same?

File: extensions/variants_test.go [hunk 2]
```diff
@@ -470,3 +470,330 @@ func TestResolveTypeErrorHandling(t *testing.T) {
...
+			&types.Int32Type{},
+			&types.StringType{},
+		}
+
+		err := extensions.ValidateConstrainedAnyTypeConsistency(params, args, nil)
+		require.NoError(t, err)
+	})
+
+	t.Run("multiple any parameters can have different types", func(t *testing.T) {
+		// func(any1, any2) with (i32, i64) - any1 != any2 is OK
```
Comment (asolimando) [inline extensions/variants_test.go]: Test with func(any1, any2) with (i32, i32)? (expected to pass)

**Review by asolimando — APPROVED** [review]
LGTM, a couple of questions for a few possible test cases to add, but this looks great!

File: testcases/parser/parse_test.go [hunk 3]
```diff
@@ -850,6 +850,21 @@ func TestLoadAllSubstraitTestFiles(t *testing.T) {
 			require.NotNil(t, testFile)
 			reg, funcRegistry := functions.NewExtensionAndFunctionRegistries(extensions.GetDefaultCollectionWithNoError())
 			for _, tc := range testFile.TestCases {
+				// TODO: Remove this skip once https://github.com/substrait-io/substrait/pull/893 is merged
```
[the remark this answers is not in the document]
Comment (benbellick) [reply testcases/parser/parse_test.go]: The above is fixed so I should be able to do away with this in this PR.

**Review by bvolpato-dd — APPROVED** [review]
This looks great to me! Thanks Ben 🙇

**Review by bvolpato — APPROVED** [review]
This looks great to me! Thanks Ben 🙇
